// const fs = require("fs");
// const path = require("path");
import fs from "node:fs";
import path from "node:path";

const __dirname = import.meta.dirname;
const IMAGES_DIR = path.join(__dirname, ".", "images");
const OUT_FILE = path.join(__dirname, "scripts", "svg.js");

function sanitizeName(name) {
  // remove extension, replace non-alnum with underscore, ensure doesn't start with digit
  let base = name.replace(/\.[^.]+$/, "");
  base = base.replace(/[^a-zA-Z0-9_$]/g, "_");
  if (/^[0-9]/.test(base)) base = "_" + base;
  return base;
}

function walk(dir) {
  let results = [];
  const list = fs.readdirSync(dir);
  list.forEach((file) => {
    const fp = path.join(dir, file);
    const stat = fs.statSync(fp);
    if (stat && stat.isDirectory()) {
      results = results.concat(walk(fp));
    } else if (/\.svg$/i.test(file)) {
      results.push(fp);
    }
  });
  return results;
}

function replaceColors(svgText) {
  // Replace fill attributes except "none" and "currentColor" and "transparent"
  svgText = svgText.replace(/fill\s*=\s*"(?!transparent)([^\"]*)"/gi, "");
  svgText = svgText.replace(/fill\s*=\s*'(?!transparent)([^\']*)'/gi, "");
  // Replace stroke attributes
  svgText = svgText.replace(/stroke\s*=\s*"([^\"]*)"/gi, "");
  svgText = svgText.replace(/stroke\s*=\s*'([^\']*)'/gi, "");
  // Replace style occurrences of fill:... and stroke:...
  svgText = svgText.replace(/(style\s*=\s*"[^"]*)fill\s*:\s*[^;\"]*/gi, (m, p1) => p1 + "");
  svgText = svgText.replace(/(style\s*=\s*'[^']*)fill\s*:\s*[^;\']*/gi, (m, p1) => p1 + "");
  svgText = svgText.replace(/(style\s*=\s*"[^"]*)stroke\s*:\s*[^;\"]*/gi, (m, p1) => p1 + "");
  svgText = svgText.replace(/(style\s*=\s*'[^']*)stroke\s*:\s*[^;\']*/gi, (m, p1) => p1 + "");
  // Also replace fill:#xxxx inside inline styles without style attr (rare)
  svgText = svgText.replace(/fill\s*:\s*#([0-9a-fA-F]{3,6})/gi, "");
  svgText = svgText.replace(/stroke\s*:\s*#([0-9a-fA-F]{3,6})/gi, "");

  return svgText;
}

function makeTemplateLiteral(str) {
  // escape backticks and ${
  return str.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function main() {
  const files = walk(IMAGES_DIR);
  const names = new Map();
  const entries = [];

  files.forEach((fp) => {
    const content = fs.readFileSync(fp, "utf8");
    let svg = content.trim();
    svg = replaceColors(svg);

    const base = sanitizeName(path.basename(fp));
    let name = base;
    let idx = 1;
    while (names.has(name)) {
      name = `${base}_${idx++}`;
    }
    names.set(name, true);

    svg = makeTemplateLiteral(svg);
    entries.push({ name, svg, file: fp });
  });

  // Build output
  const header =
    `// Auto-generated by scripts/generate_svgs.js - do not edit by hand\n` +
    `// Generated: ${new Date().toISOString()}\n\n`;

  let out = header;
  entries.forEach((e) => {
    out += `export const ${e.name} = ` + "`" + `${e.svg}` + "`" + `;\n\n`;
  });

  // Optionally export all
  out += `export default {` + entries.map((e) => ` ${e.name}`).join(",") + ` };\n`;

  fs.writeFileSync(OUT_FILE, out, "utf8");
  console.log("Wrote", OUT_FILE, "with", entries.length, "entries");
}

main();
