name: Deploy Web Folder

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload web folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web

      - name: Deploy
        uses: actions/deploy-pages@v4